build.yml file updated for decode keystore

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -30,27 +30,16 @@ jobs:
       - name: Setup Android SDK
         uses: android-actions/setup-android@v2
 
-      - name: Decode Keystore
-        run: |
-          mkdir -p android/keystore
-          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/keystore/release-key.jks
-          test -f android/keystore/release-key.jks || (echo "Keystore decode failed" && exit 1)
-        env:
-          KEYSTORE_PATH: /home/runner/work/shopq-demo-cicd/shopq-demo-cicd/android/keystore/release-key.jks
-          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
-          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
-          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
-
-      - name: Print signing env (debug only)
-        run: |
-          echo "KEYSTORE_PASSWORD: ${KEYSTORE_PASSWORD}"
-          echo "KEY_ALIAS: ${KEY_ALIAS}"
-          echo "KEY_PASSWORD: ${KEY_PASSWORD}"
-        env:
-          KEYSTORE_PATH: /home/runner/work/shopq-demo-cicd/shopq-demo-cicd/android/keystore/release-key.jks
-          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
-          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
-          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
+      # - name: Decode Keystore
+      #   run: |
+      #     mkdir -p android/keystore
+      #     echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > /home/runner/work/shopq-demo-cicd/shopq-demo-cicd/android/keystore/release-key.jks
+      #     test -f android/keystore/release-key.jks || (echo "Keystore decode failed" && exit 1)
+      #   env:
+      #     KEYSTORE_PATH: /home/runner/work/shopq-demo-cicd/shopq-demo-cicd/android/keystore/release-key.jks
+      #     KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
+      #     KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
+      #     KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
 
       - name: Make gradlew executable
         run: chmod +x android/gradlew
